name: Build & deploy

env:
  # Change this to upload the built image to your own organization.
  docker_tag: 'fundi.azurecr.io/ilmomasiina'

  # Change these to customize your build.
  branding_header_title_text: 'Fundin Ilmomasiina'
  branding_footer_gdpr_text: 'Tietosuoja'
  branding_footer_gdpr_link: 'https://fundi.fi/tietosuoja'
  branding_footer_home_text: 'Fundi ry'
  branding_footer_home_link: 'https://fundi.fi'
  branding_login_placeholder_email: 'big.boss@fundi.fi'


on:
  push:
    branches:
      - prod
    tags:
      - 'v*'

jobs:
  lint:
    name: Lint & type-check
    uses: ./.github/workflows/lint.yml

  docker:
    name: Push Docker image to GitHub Packages
    needs: lint
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    # Change this to your repo name to build automatically on your fork.
    if: github.repository == 'Onyx-Solutions-Oy/ilmomasiina-fundi'
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: fundi.azurecr.io
          username: ${{ secrets.ACR_USERNAME }} # Your ACR username stored in GitHub secrets
          password: ${{ secrets.ACR_PASSWORD }} # Your ACR password stored in GitHub secrets
      -
        name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.docker_tag }}
          flavor: |
            latest=${{ github.ref == 'refs/heads/prod' }}
          tags: |
            type=semver,pattern={{version}},enable=${{ github.ref_type == 'tag' }}
            type=semver,pattern={{major}}.{{minor}},enable=${{ github.ref_type == 'tag' }}
            type=ref,event=branch,enable=${{ github.ref_type == 'branch' }}
            type=sha
      -
        name: Push to Azure Container Registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BRANDING_HEADER_TITLE_TEXT=${{ env.branding_header_title_text }}
            BRANDING_FOOTER_GDPR_TEXT=${{ env.branding_footer_gdpr_text }}
            BRANDING_FOOTER_GDPR_LINK=${{ env.branding_footer_gdpr_link }}
            BRANDING_FOOTER_HOME_TEXT=${{ env.branding_footer_home_text }}
            BRANDING_FOOTER_HOME_LINK=${{ env.branding_footer_home_link }}
            BRANDING_LOGIN_PLACEHOLDER_EMAIL=${{ env.branding_login_placeholder_email }}
